# Generated by Django 4.1.4 on 2023-01-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.PositiveIntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('sdept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.department')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('tdept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.department')),
            ],
        ),
        migrations.DeleteModel(
            name='habit',
        ),
        migrations.AddField(
            model_name='student',
            name='stname',
            field=models.ManyToManyField(to='reg.teacher'),
        ),
    ]
