# Generated by Django 4.1.4 on 2023-01-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_department_student_teacher_delete_habit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stname',
        ),
    ]
